[package]
name = "rviewerable_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = { version = "2.0.15", features = ["derive", "parsing", "extra-traits"] }
